# Generated by Django 5.1.3 on 2025-08-06 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.BigIntegerField(default=0, null=True)),
                ('is_system_owner', models.BooleanField(default=False)),
                ('is_office', models.BooleanField(default=False)),
                ('is_person', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SafeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Crypto', 'Crypto'), ('Physical', 'Physical')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SafePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_usdt', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_iqd', models.BigIntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safe_balances', to='api.partner')),
                ('safe_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.safetype')),
            ],
            options={
                'unique_together': {('partner', 'safe_type')},
            },
        ),
        migrations.CreateModel(
            name='OutgoingMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5)),
                ('from_name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('taker_name', models.CharField(max_length=100)),
                ('my_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('partner_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bonus_currency', models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_from', to='api.safepartner')),
                ('to_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_to', to='api.safepartner')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5)),
                ('to_name', models.CharField(blank=True, max_length=100, null=True)),
                ('to_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('my_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('partner_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bonus_currency', models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_from', to='api.safepartner')),
                ('to_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_to', to='api.safepartner')),
            ],
        ),
        migrations.CreateModel(
            name='SafeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Add (Deposit)'), ('REMOVE', 'Remove (Withdrawal)')], max_length=6)),
                ('money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(choices=[('USDT', 'USDT'), ('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.safepartner')),
            ],
        ),
        migrations.CreateModel(
            name='TransferExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_type', models.CharField(choices=[('USD_TO_IQD', 'USD to IQD'), ('IQD_TO_USD', 'IQD to USD')], max_length=10)),
                ('usd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('iqd_amount', models.BigIntegerField(default=0)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.safepartner')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=10)),
                ('usdt_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('usdt_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bonus_currency', models.CharField(choices=[('USDT', 'USDT'), ('USD', 'USD'), ('IQD', 'IQD')], max_length=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('currency', models.CharField(choices=[('USDT', 'USDT'), ('USD', 'USD'), ('IQD', 'IQD')], max_length=5)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.safepartner')),
                ('crypto_safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crypto_wallet_safe', to='api.safetype')),
                ('payment_safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crypto_payment_safe', to='api.safetype')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'transaction_type'], name='api_cryptot_status_37b6b9_idx'), models.Index(fields=['partner', 'status'], name='api_cryptot_partner_17a68e_idx')],
            },
        ),
    ]
