# Generated by Django 5.1.3 on 2025-08-25 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=100)),
                ('debtor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_safe', to='api.safetype')),
            ],
        ),
        migrations.CreateModel(
            name='DebtRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='api.debt')),
            ],
        ),
    ]
