# Generated by Django 5.1.3 on 2025-08-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_partner_phone_number_debt_debtrepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferexchange',
            name='bonus_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='transferexchange',
            name='my_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
