# Generated by Django 5.1.3 on 2025-08-29 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transferexchange_bonus_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptotransaction',
            name='partner_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.partner'),
        ),
    ]
