# Generated by Django 5.1.3 on 2025-09-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cryptotransaction_partner_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptotransaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crypto_partner', to='api.safepartner'),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='partner_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crypto_client', to='api.safepartner'),
        ),
        migrations.CreateModel(
            name='SafePartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Add (Deposit)'), ('REMOVE', 'Remove (Withdrawal)')], max_length=6)),
                ('money_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(choices=[('USDT', 'USDT'), ('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.safepartner')),
            ],
        ),
    ]
