# Generated by Django 5.1.3 on 2025-09-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cryptotransaction_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='safe_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='api.safepartner'),
        ),
        migrations.AddField(
            model_name='debtrepayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD'), ('USDT', 'USDT')], default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debtor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
