# Generated by Django 5.1.3 on 2025-09-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_debt_safe_partner_debtrepayment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtrepayment',
            name='safe_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_safe_repayments', to='api.safetype'),
        ),
        migrations.AlterField(
            model_name='debtrepayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('USDT', 'USDT')], default='USD', max_length=5),
        ),
    ]
