# Generated by Django 5.1.3 on 2025-09-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_debtrepayment_safe_type_alter_debtrepayment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetransaction',
            name='from_safepartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='api.safepartner'),
        ),
        migrations.AddField(
            model_name='safetransaction',
            name='to_safepartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='api.safepartner'),
        ),
        migrations.AlterField(
            model_name='safetransaction',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.safepartner'),
        ),
        migrations.AlterField(
            model_name='safetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add (Deposit)'), ('REMOVE', 'Remove (Withdrawal)'), ('TRANSFER', 'Transfer')], max_length=8),
        ),
        migrations.DeleteModel(
            name='SafePartnerTransaction',
        ),
    ]
