# Generated by Django 5.1.3 on 2025-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_safetransaction_from_safepartner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtrepayment',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Rate to convert repayment currency to debt currency', max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptotransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='debt',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='debtrepayment',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT'), ('USD', 'USD'), ('IQD', 'IQD')], default='USD', max_length=5),
        ),
    ]
