# Generated by Django 5.1.3 on 2025-09-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_debtrepayment_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmoney',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
