# Generated by Django 5.1.3 on 2025-09-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_outgoingmoney_is_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmoney',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
    ]
