# Generated by Django 5.1.3 on 2025-09-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_incomingmoney_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safepartner',
            name='total_iqd',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='safetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ADD', 'Add (Deposit)'), ('REMOVE', 'Remove (Withdrawal)'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=8),
        ),
    ]
