# Generated by Django 5.1.3 on 2025-09-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_safepartner_total_iqd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safepartner',
            name='total_iqd',
            field=models.BigIntegerField(default=0),
        ),
    ]
